// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSk2guVcc-A6S8R8g8GIy0YPjIMXNtBcE',
    appId: '1:27342338334:web:1f7e361b634cd9ae26310f',
    messagingSenderId: '27342338334',
    projectId: 'flutter-chat-app-bd0f6',
    authDomain: 'flutter-chat-app-bd0f6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bd0f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBGn9smVy8tNN_4HickC2D0_RYpd0ZcyQ',
    appId: '1:27342338334:android:bee5f9a9512fd02126310f',
    messagingSenderId: '27342338334',
    projectId: 'flutter-chat-app-bd0f6',
    storageBucket: 'flutter-chat-app-bd0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZfjKxFtIJbewFA_v1ceMV-19AT54EL8',
    appId: '1:27342338334:ios:1ab8db0977f77a0526310f',
    messagingSenderId: '27342338334',
    projectId: 'flutter-chat-app-bd0f6',
    storageBucket: 'flutter-chat-app-bd0f6.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ZfjKxFtIJbewFA_v1ceMV-19AT54EL8',
    appId: '1:27342338334:ios:1ab8db0977f77a0526310f',
    messagingSenderId: '27342338334',
    projectId: 'flutter-chat-app-bd0f6',
    storageBucket: 'flutter-chat-app-bd0f6.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSk2guVcc-A6S8R8g8GIy0YPjIMXNtBcE',
    appId: '1:27342338334:web:2339c1266d0747e226310f',
    messagingSenderId: '27342338334',
    projectId: 'flutter-chat-app-bd0f6',
    authDomain: 'flutter-chat-app-bd0f6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bd0f6.appspot.com',
  );
}